AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM User for my home server'


Resources:
  M910QServer:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: 'server-m910q'
      Policies:
        - PolicyName: 'certbot-dns01-challange'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'route53:ListHostedZones'
                  - 'route53:GetChange'
                Effect: Allow
                Resource:
                  - '*'
              - Action:
                  - 'route53:ChangeResourceRecordSets'
                Effect: Allow
                Resource:
                  - 'arn:aws:route53:::hostedzone/ZW94R9XFGJ0MX'
