AWSTemplateFormatVersion: '2010-09-09'
Description: The root records for the flaviopogliani.net zone


Parameters:
  HostedZoneID:
    Description: The ID of the Hosted Zone for the domain.
    Type: String
    Default: Z1CVRNQ0YYAYLS


Resources:
  MailExchangeRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'flaviopogliani.net.'
      ResourceRecords:
        - '0 mail5.hostinguk.net.'
      TTL: 300
      Type: 'MX'

  SpfRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'flaviopogliani.net.'
      ResourceRecords:
        - '"v=spf1 a mx include:hostinguk.net -all"'
      TTL: 300
      Type: 'TXT'

  WebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: 'd1i8g3nyi3b88o.cloudfront.net'
        HostedZoneId: 'Z2FDTNDATAQYW2'  # Magic Value provided by AWS.
      HostedZoneId: !Ref HostedZoneID
      Name: 'flaviopogliani.net.'
      Type: 'A'

  WwwWebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: 'd1i8g3nyi3b88o.cloudfront.net'
        HostedZoneId: 'Z2FDTNDATAQYW2'  # Magic Value provided by AWS.
      HostedZoneId: !Ref HostedZoneID
      Name: 'www.flaviopogliani.net.'
      Type: 'A'

  WebSiteCertificateValidationRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_bebf861b371e844c43d92872543097d0.flaviopogliani.net.'
      ResourceRecords:
        - '_792cafd2531a013d9ee3de10e678900e.jfrzftwwjs.acm-validations.aws.'
      TTL: 86400  # 24 Hours TTL
      Type: 'CNAME'

  WwwWebSiteCertificateValidationRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_b1995d2e4abb1209e04f0bdd6b6ff3c6.www.flaviopogliani.net.'
      ResourceRecords:
        - '_ef266e2c1f4b4a70cba900ae5e8f6e18.jfrzftwwjs.acm-validations.aws.'
      TTL: 86400  # 24 Hours TTL
      Type: 'CNAME'
