AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS Certificate Manager validation records for the bbPerledo.io zone


Parameters:
  HostedZoneID:
    Description: The ID of the Hosted Zone for the domain.
    Type: String
    Default: Z1A8B2PKGVNMFR


Resources:
  ValidateRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_e3da23ea0648b6071ba302a1aab128d8.bbperledo.net.'
      ResourceRecords:
        - '_b68478dd44d6226e813a1b38fe8aa873.ltfvzjuylp.acm-validations.aws.'
      TTL: 3600
      Type: 'CNAME'

  WwwValidateRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_dcda1715a3dde2429e1004c09ad29403.www.bbperledo.net.'
      ResourceRecords:
        - '_a87b761fb411fa1cf6f8ced32034237f.ltfvzjuylp.acm-validations.aws.'
      TTL: 3600
      Type: 'CNAME'
