AWSTemplateFormatVersion: '2010-09-09'
Description: The root records for the spogliani.net zone


Parameters:
  HostedZoneID:
    Description: The ID of the Hosted Zone for the domain.
    Type: String
    Default: ZW94R9XFGJ0MX


Resources:
  MailExchangeRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'spogliani.net.'
      ResourceRecords:
        - '0 mail5.hostinguk.net.'
      TTL: 300
      Type: 'MX'

  SpfRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'spogliani.net.'
      ResourceRecords:
        - '"v=spf1 a mx include:hostinguk.net include:amazonses.com -all"'
      TTL: 300
      Type: 'TXT'

  WebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'spogliani.net.'
      ResourceRecords:
        - '185.199.108.153'
        - '185.199.109.153'
        - '185.199.110.153'
        - '185.199.111.153'
      TTL: 14400  # 4 Hours TTL
      Type: 'A'

  WwwWebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'www.spogliani.net.'
      ResourceRecords:
        - 'stefano-pogliani.github.io'
      TTL: 14400  # 4 Hours TTL
      Type: 'CNAME'
