AWSTemplateFormatVersion: '2010-09-09'
Description: The root records for the trecamini.net zone


Parameters:
  HostedZoneID:
    Description: The ID of the Hosted Zone for the domain.
    Type: String
    Default: Z3IRV9DEY0YXMW


Resources:
  MailExchangeRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'trecamini.net.'
      ResourceRecords:
        - '0 mail5.hostinguk.net.'
      TTL: 300
      Type: 'MX'

  SpfRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: 'trecamini.net.'
      ResourceRecords:
        - '"v=spf1 a mx include:hostinguk.net -all"'
      TTL: 300
      Type: 'TXT'

  WebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: 'dxl3ls2bmlxfu.cloudfront.net'
        HostedZoneId: 'Z2FDTNDATAQYW2'  # Magic Value provided by AWS.
      HostedZoneId: !Ref HostedZoneID
      Name: 'trecamini.net.'
      Type: 'A'

  WwwWebSiteRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: 'dxl3ls2bmlxfu.cloudfront.net'
        HostedZoneId: 'Z2FDTNDATAQYW2'  # Magic Value provided by AWS.
      HostedZoneId: !Ref HostedZoneID
      Name: 'www.trecamini.net.'
      Type: 'A'

  WebSiteCertificateValidationRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_3d1e18cdca980d886c2165af80a5d6e4.trecamini.net.'
      ResourceRecords:
        - '_c975a10b0b6701ddc61425cf34dce4ab.jfrzftwwjs.acm-validations.aws.'
      TTL: 86400  # 24 Hours TTL
      Type: 'CNAME'

  WwwWebSiteCertificateValidationRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: '_38f3a512a53b907d13e338f7b83719e8.www.trecamini.net.'
      ResourceRecords:
        - '_1b65ac98458bd292135056560ad3ff0f.jfrzftwwjs.acm-validations.aws.'
      TTL: 86400  # 24 Hours TTL
      Type: 'CNAME'
